app/client/urls.py
from django.urls import path

from client import views

app_name = 'client'

urlpatterns = [
    path('dashboard/', views.ClientDashboardView.as_view(), name='dashboard'),
    path(
        'article-detail/<slug:slug>/',
        views.ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'browse-articles/',
        views.BrowseArticlesView.as_view(),
        name='browse_articles'),
    path(
        'subscription-plans/',
        views.SubscriptionPlansView.as_view(),
        name='subscription_plans'
    ),
    path(
        'create-subscription/',
        views.CreateSubscriptionView.as_view(),
        name='create_subscription'),
    path(
        'delete-subscription/<str:subID>/',
        views.DeleteSubscriptionView.as_view(),
        name='delete_subscription'
    ),
    path(
        'update-subscription/<str:sub_id>/',
        views.UpdateSubscriptionView.as_view(),
        name='update_subscription'
    ),
    path(
        'paypal-subscription-confirmed/',
        views.PayPalSubConfirmedView.as_view(),
        name='paypal_subscription_confirmed'
    ),
    path(
        'django-subscription-confirmed/<str:subID>/',
        views.DjangoSubConfirmedView.as_view(),
        name='django_subscription_confirmed'
    ),
    path('deactivate-subscription/<str:sub_id>/',
         views.deactivate_subscription,
         name='deactivate_subscription'
    ),
    path(
        'activate-subscription/<str:sub_id>/',
        views.activate_subscription,
        name='activate_subscription'
    ),
]

app/core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

app/subplatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('client/', include('client.urls', namespace='client')),
    path('writer/', include('writer.urls', namespace='writer')),
]

app/writer/urls.py
from django.urls import path

from writer import views

app_name = 'writer'

urlpatterns = [
    path(
        '<int:writer_id>/dashboard/',
        views.WriterDashboardView.as_view(),
        name='dashboard'
    ),
    path(
        '<int:writer_id>/create-article/',
        views.CreateArticleView.as_view(),
        name='create_article'
    ),
    path(
        '<int:writer_id>/my-articles/',
        views.MyArticlesView.as_view(),
        name='my_articles'
    ),
    path(
        '<int:writer_id>/update-article/<slug:slug>/',
        views.UpdateArticleView.as_view(),
        name='update_article'
    ),
    path(
        '<int:writer_id>/delete-article/<slug:slug>/',
        views.delete_article,
        name='delete_article'
    ),
]

app/client/models.py
from django.db import models

from django.contrib.auth import get_user_model


class SubscriptionPlan(models.Model):
    paypal_plan_id = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255, unique=True)
    cost = models.DecimalField(decimal_places=2, max_digits=5)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'subscription plan'
        verbose_name_plural = 'subscription plans'

    def __str__(self):
        return f'{self.name}'


class Subscription(models.Model):
    subscriber_name = models.CharField(max_length=255)
    subscription_plan = models.ForeignKey(
        SubscriptionPlan,
        on_delete=models.CASCADE,
        related_name='subscription_plan'
    )
    paypal_subscription_id = models.CharField(max_length=300)
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='subscription',
        max_length=10,
        unique=True
    )
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return (f'{self.subscriber_name} - '
                f'{self.subscription_plan.name.capitalize()} subscription')

app/client/views.py
from django.db import IntegrityError
from django.shortcuts import redirect, reverse, get_object_or_404

from django.views.generic import TemplateView, DetailView, ListView, RedirectView

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator

from writer.models import Article

from client.models import Subscription, SubscriptionPlan
from client.exceptions import SubscriptionNotDeletedException
from client.paypal import (get_access_token,
                           cancel_subscription_paypal,
                           update_subscription_paypal,
                           get_current_subscription_plan,
                           deactivate_subscription_paypal,
                           activate_subscription_paypal)


class ClientDashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'client/client_dashboard.html'
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_writer:  # noqa
            return redirect(reverse(
                'writer:dashboard',
                kwargs={'writer_id': request.user.id}
            ))

        return super(ClientDashboardView, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        subscriptions = Subscription.objects.filter(
            user=self.request.user,
            # is_active=True
        ).order_by('-id')

        if subscriptions.exists():
            context['sub_plan'] = subscriptions[0].subscription_plan

        context['title'] = 'Edenthought | Dashboard'

        return context


class ArticleDetailView(LoginRequiredMixin, DetailView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    model = Article
    template_name = 'client/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Edenthought | {self.get_object().title}'
        return context


class BrowseArticlesView(LoginRequiredMixin, ListView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    template_name = 'client/browse_articles.html'

    queryset = Article.objects.all().order_by('-date_posted')
    context_object_name = 'articles'

    def get_queryset(self):
        user = self.request.user

        if (not hasattr(user, 'subscription') or
            not user.subscription or # noqa
            not user.subscription.is_active):  # noqa

            return None

        if user.subscription.subscription_plan.name == 'standard':  # noqa
            return self.queryset.filter(is_premium=False)

        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Articles'
        return context


class SubscriptionPlansView(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    template_name = 'client/subscription_plans.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Subscription Plans'
        return context


class CreateSubscriptionView(LoginRequiredMixin, RedirectView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    pattern_name = 'client:dashboard'

    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        sub_id = self.request.GET.get('subID')
        plan_name = self.request.GET.get('plan')
        plan = get_object_or_404(SubscriptionPlan, name=plan_name)

        try:
            Subscription.objects.create(
                user=user,
                subscriber_name=user.full_name(),  # noqa
                subscription_plan=plan,
                paypal_subscription_id=sub_id,
                is_active=True
            )
            messages.success(self.request, 'Subscription created successfully!')

        except IntegrityError:
            messages.error(
                self.request,
                'Subscription not created! Invalid data has been submitted.'
            )
        except Exception as e:
            messages.error(self.request, f'Something went wrong!\n{e}')

        return super().get_redirect_url(*args, **kwargs)


class DeleteSubscriptionView(TemplateView):
    template_name = 'client/delete_subscription.html'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        sub_id = self.kwargs.get('subID')

        return super(DeleteSubscriptionView, self).dispatch(
            request,
            sub_id,
            *args,
            **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Delete Subscription'

        sub_id = self.kwargs.get('subID')

        # Delete subscription from PayPal
        access_token = get_access_token()

        try:
            cancel_subscription_paypal(access_token, sub_id)
        except SubscriptionNotDeletedException:
            context['is_deleted'] = False

        else:
            # Delete subscription from Django (application side)
            subscription = get_object_or_404(
                Subscription,
                user=self.request.user,
                paypal_subscription_id=sub_id
            )
            subscription.delete()
            context['is_deleted'] = True

        return context


class UpdateSubscriptionView(RedirectView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateSubscriptionView, self).dispatch(
            request,
            self.kwargs['sub_id'],
            *args,
            **kwargs
        )

    def get_redirect_url(self, *args, **kwargs):
        access_token = get_access_token()
        approve_link = update_subscription_paypal(
            access_token,
            sub_id=self.kwargs.get('sub_id', None)
        )
        if approve_link:
            messages.success(self.request, 'Subscription updated successfully!')
            return approve_link

        messages.error(self.request, 'Something went wrong!')
        return reverse('account')


class PayPalSubConfirmedView(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    template_name = 'client/paypal_update_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'PayPal Confirmed Subscription'

        subscription = Subscription.objects.filter(user=self.request.user)
        if subscription.exists():
            context['subID'] = subscription[0].paypal_subscription_id

        return context


class DjangoSubConfirmedView(TemplateView):
    template_name = 'client/django_update_confirmed.html'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        sub_id = self.kwargs.get('subID')

        return super().dispatch(
            request,
            sub_id,
            *args,
            **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Subscription Confirmed'

        subscription = get_object_or_404(
            Subscription,
            user=self.request.user,
            paypal_subscription_id=self.kwargs.get('subID')
        )
        access_token = get_access_token()
        paypal_subscription_plan_id = get_current_subscription_plan(
            access_token,
            self.kwargs['subID']
        )
        current_subscription_plan_id = subscription.subscription_plan.paypal_plan_id

        if paypal_subscription_plan_id != current_subscription_plan_id:
            new_plan = get_object_or_404(
                SubscriptionPlan,
                paypal_plan_id=paypal_subscription_plan_id
            )

            subscription.subscription_plan = new_plan
            subscription.save()

        context['subPlan'] = subscription.subscription_plan

        return context


@login_required(
    login_url='login',
    redirect_field_name='redirect_to'
)
def deactivate_subscription(request, sub_id):
    """Deactivate a subscription of a client."""

    access_token = get_access_token()
    status_code = deactivate_subscription_paypal(access_token, sub_id)

    if status_code == 204:
        subscription = get_object_or_404(
            Subscription,
            paypal_subscription_id=sub_id
        )
        subscription.is_active = False
        subscription.save()

        messages.success(request, 'Subscription deactivated successfully!')
        return redirect('client:dashboard')

    messages.error(request, 'Something went wrong!')
    return redirect(request.META.get('HTTP_REFERER', reverse('client:dashboard')))


@login_required(
    login_url='login',
    redirect_field_name='redirect_to'
)
def activate_subscription(request, sub_id):
    """Activate a subscription of a client."""

    access_token = get_access_token()
    status_code = activate_subscription_paypal(access_token, sub_id)

    if status_code == 204:
        subscription = get_object_or_404(
            Subscription,
            paypal_subscription_id=sub_id
        )
        subscription.is_active = True
        subscription.save()

app/client/templates/client/article_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% if user.is_writer%}
    {% include 'writer/includes/writer_menu.html' %}
  {% else %}
    {% include 'client/includes/client_menu.html' %}
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container bg-white shadow my-2 my-md-4 p-5">
    <h1 class="text-center">{{ article.title }}</h1>

    {% if article.is_premium %}
      <h6>🪙 Premium article 🪙</h6>
    {% endif %}

    <br>
    <div>
      {{ article.content }}
    </div>
    <br>
    <div class="justify-content-end">

        Author: {{ article.author.first_name }} {{ article.author.last_name }}
        <br>
        Published: {{ article.date_posted|date:"M j, Y" }} - {{ article.date_posted|time:"H:i:s" }}

    </div>

  {% if user.is_writer %}
    <div class="update">
      <div>
        <a href="{% url 'writer:update_article' user.id article.slug %}">
          ⚙️ Update article
        </a>
      </div>

      <div class="delete-article">
        <a type="button" data-toggle="modal" data-target="#deleteModalCenter">
          🚫 Delete article
        </a>
      </div>

      {% include 'writer/includes/delete_modal.html' %}
    </div>

  {% endif %}

  </div>

{% endblock %}

app/client/templates/client/browse_articles.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  {% if articles %}

    <div class="container shadow bg-white my-4 my-md-5 pt-4 pb-3">
      <h3 class="text-center">Articles</h3>
    </div>

    {% for article in articles %}

        <div class="container shadow bg-white my-3 my-md-4 p-4 form-layout">
          <a href="{% url 'client:article_detail' article.slug %}">
            <div>
              <h3> {{ article.title }} </h3>

              {% if article.is_premium %}
                <h6>🪙 Premium article 🪙</h6>
              {% endif %}

              <br>
              <p>{{ article.content|slice:"0:150" }}...</p>

              <br>
              <div class="datetime">
                {{ article.date_posted|date:"M j, Y" }} - {{ article.date_posted|time:"H:i:s" }}
              </div>
            </div>
          </a>
        </div>

    {% endfor %}

{#  {% else %}#}
{##}
{#    <div class="container text-center my-4 my-md-5">#}
{#      <div class="empty-list">#}
{#        You have no active subscription plan yet. <br>#}
{#        Please, subscribe to browse through your articles!#}
{#      </div>#}
{#      <a href="{% url 'client:subscription-plans' %}"#}
{#         class="btn btn-success mt-5"#}
{#         type="button">#}
{#        Get subscription plan#}
{#      </a>#}
{#    </div>#}

  {% endif %}

{% endblock %}

app/client/templates/client/client_dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container bg-white shadow mt-2 mt-md-4 p-5 form-layout text-center">
    <h5>👋 Welcome, {{ user.first_name }}!</h5>
    <p class="mt-4">
      As a <span class="accent">client</span> you can browse through standard
      and premium articles.
    </p>
  </div>

  <div class="container bg-white shadow mt-2 mt-md-4 p-5 form-layout text-center">
    <h5>Subscription status:</h5>
    {% if sub_plan %}
      <p class="pt-3 fw-bold">
        {{ sub_plan.name|title }}
        <a href="{% url 'account' %}#edit-subscription" class="fw-light">(✒️ edit)</a>
      </p>
    {% else %}
      <p class="py-3">None</p>
      <form action="{% url 'client:subscription_plans' %}" method="get">
        <input type="submit"
               value="Subscribe"
               class="btn btn-success">
      </form>
    {% endif %}
  </div>

{% endblock %}

app/client/templates/client/delete_subscription.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container form-layout bg-white shadow text-center p-5 my-4 my-md-5">
  {% if is_deleted %}
    <h5>Subscription cancelled!</h5>
    <br>
    <h1>✔️</h1>
    <br>
    <p>
      We regret to inform you that your subscription has been cancelled as
      per your request. <br>
      Thank you for your past support!
    </p>
  {% else %}
    <h5>Something went wrong!</h5>
    <br>
    <h1>🧐</h1>
    <br>
    <p>
      We could not cancel your subscription properly. <br>
      Please, check if you have any subscription by now.
    </p>
  {% endif %}

    <a class="btn btn-success mt-4 mt-md-5" href="{% url 'client:dashboard' %}">
      Return to dashboard
    </a>
  </div>

{% endblock %}

app/client/templates/client/django_update_confirmed.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container form-layout bg-white shadow text-center p-5 my-4 my-md-5">

    <h5>Application approval confirmed!</h5>
    <br>
    <h1>✅</h1>
    <br>
    <p>
      Your request to update your subscription has been confirmed on your account!
    </p>

    <a class="btn btn-success mt-4 mt-md-5" href="{% url 'client:dashboard' %}">
      Return to dashboard
    </a>
  </div>

{% endblock %}

app/client/templates/client/paypal_update_confirmed.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container form-layout bg-white shadow text-center p-5 my-4 my-md-5">

    <h5>PaPal update confirmed!</h5>
    <br>
    <h1>✅</h1>
    <br>
    <p>
      Your request to update your subscription has been confirmed on PayPal!
    </p>

    <a class="btn btn-success mt-4 mt-md-5" href="#">  <!-- url 'client:django-subscription-confirmed' subID=subID -->
      Confirm for final approval
    </a>
  </div>

{% endblock %}

app/client/templates/client/subscription_plans.html
{% extends 'core/base.html' %}
{% load static %}

{% block menu %}
  {% include 'client/includes/client_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container shadow bg-white my-4 my-md-5 pt-4 pb-3">
    <h3 class="text-center">Subscription Plans</h3>
  </div>

  <br>

  <div class="container">
    <div class="row justify-content-sm-around">
      <div class="form-layout bg-white shadow p-5 m-3 text-center">
        <h5 class="plan-title">Standard subscription</h5>

        <p>Join us for standard access here:</p>
        <span class="plan-descr fw-bold">(Limited article access)</span>

        <h2 class="plan-price my-4">$4.99</h2>

        <!-- PayPal buttons -->

        {% if not user.subscription %}
        <div id="paypal-button-container-P-9EN41519BU401782AM7HQXXI"
             class="paypal-buttons pt-4"></div>
        {% else %}
          <form action="#" method="get" class="bnt-form">
            <input type="button"
                   value="Update current subscription"
                   data-toggle="modal"
                   data-target="#updateSubModal"
                   class="btn btn-info">
            {% include 'client/includes/update_sub_modal.html' %}
          </form>
        {% endif %}
      </div>

      <div class="form-layout bg-white shadow p-5 m-3 text-center">
        <h5 class="plan-title">Premium subscription</h5>

        <p>Join us for premium access here:</p>
        <span class="plan-descr fw-bold">(Full article access)</span>

        <h2 class="plan-price my-4">$9.99</h2>

        <!-- PayPal buttons -->

        {% if not user.subscription %}
          <div id="paypal-button-container-P-2JB54269VP863135RM7HQZFY"
               class="paypal-buttons pt-4"></div>
        {% else %}
          <form action="#" method="get" class="bnt-form">
            <input type="button"
                   value="Update current subscription"
                   data-toggle="modal"
                   data-target="#updateSubModal"
                   class="btn btn-info">
            {% include 'client/includes/update_sub_modal.html' %}
          </form>
        {% endif %}
      </div>

    </div>
  </div>

  <!-- CLIENT ID -->
  <script src="https://www.paypal.com/sdk/js?client-id=AaG7d8wiabvt5uO5ZNaScsgBJF0o_uMBT3zZSStguioa6jdXtgVuA9unYHjQxnsXcErSnYMiOYK71w-m&vault=true&intent=subscription" data-sdk-integration-source="button-factory"></script>

  <script>
    paypal.Buttons({
        style: {
            shape: 'pill',
            color: 'silver',
            layout: 'vertical',
            label: 'subscribe'
        },
        createSubscription: function(data, actions) {
          return actions.subscription.create({
            /* Creates the subscription */
            plan_id: 'P-9EN41519BU401782AM7HQXXI'
          });
        },
        onApprove: function(data, actions) {
            let currentUrl = '/client/create-subscription/?subID=' + data.subscriptionID + '&plan=standard'
            window.open(currentUrl, '_self')
        }
    }).render('#paypal-button-container-P-9EN41519BU401782AM7HQXXI'); // Renders the PayPal button
  </script>

  <script>
    paypal.Buttons({
        style: {
            shape: 'pill',
            color: 'gold',
            layout: 'vertical',
            label: 'subscribe'
        },
        createSubscription: function(data, actions) {
          return actions.subscription.create({
            /* Creates the subscription */
            plan_id: 'P-2JB54269VP863135RM7HQZFY'
          });
        },
        onApprove: function(data, actions) {
            let currentUrl = '/client/create-subscription/?subID=' + data.subscriptionID + '&plan=premium'
            window.open(currentUrl, '_self')
        }
    }).render('#paypal-button-container-P-2JB54269VP863135RM7HQZFY'); // Renders the PayPal button
  </script>

{% endblock %}